language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./
  on:
    branch: master